/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package toyrobot

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.fail

class CliTest {
    @Test
    fun `handles interactive option`() {
        val sut = Cli()

        sut.parse(listOf("-i"))

        assert(sut.mode is InteractiveCliMode)
    }

    @Test
    fun `handles file option`() {
        val file = File.createTempFile("test", "txt").apply {
            deleteOnExit()
            writeText("MOVE")
        }

        val mode = Cli().let {
            it.parse(listOf("-f", file.absolutePath))
            it.mode
        }

        when (mode) {
            is FileCliMode -> assertEquals(mode.lines, listOf("MOVE"))
            else -> fail()
        }
    }
}
