/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package toyrobot

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.fail

class CliTest {
    @Test
    fun `handles interactive option`() {
        val sut = Cli()

        sut.parse(listOf("-i"))

        assert(sut.mode is InteractiveMode)
    }

    @Test
    fun `handles file option`() {
        val file = File.createTempFile("test", "txt").apply {
            deleteOnExit()
        }

        val mode = Cli().run {
            parse(listOf("-f", file.absolutePath))
            mode
        }

        when (mode) {
            is FileMode -> assertEquals(mode.file.absolutePath, file.absolutePath)
            else -> fail()
        }
    }
}
