/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package toyrobot

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.fail

class CommandTest {
}

class CommandParserTest {
    @Test
    fun `parse left command`() {
        assert(Command.parse("LEFT") is LeftCommand)
    }

    @Test
    fun `parse right command`() {
        assert(Command.parse("RIGHT") is RightCommand)
    }

    @Test
    fun `parse move command`() {
        assert(Command.parse("MOVE") is MoveCommand)
    }

    @Test
    fun `parse report command`() {
        assert(Command.parse("REPORT") is ReportCommand)
    }

    @Test
    fun `parse place command`() {
        val sut = Command.parse("PLACE 1,2,NORTH")

        if (sut is PlaceCommand) {
            assertEquals(sut.x, 1)
            assertEquals(sut.y, 2)
            assertEquals(sut.facing, Direction.NORTH)
        } else
            fail()
    }

    @Test
    fun `parse invalid command`() {
        assert(Command.parse("FOO") is InvalidCommand)
    }

    @Test
    fun `parse all`() {
        val sut = Command.parseAll("LEFT", "RIGHT", "MOVE")

        assertEquals(sut, listOf(LeftCommand, RightCommand, MoveCommand))
    }
}