/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package toyrobot

import java.net.NoRouteToHostException
import kotlin.test.*

class RobotTest {
    @Test
    fun `test stringify`() {
        val sut = Robot(Pair(1, 2), Direction.NORTH)

        assertEquals("1,2,NORTH", sut.stringify())
    }
}
