/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package toyrobot

import java.net.NoRouteToHostException
import kotlin.math.exp
import kotlin.test.*

class UtilTest {
    @Test
    fun `add direction to postion (pair)`() {
        for ((pos, dir, expected) in listOf(
                Triple(Pair(1, 1), Direction.NORTH, Pair(1, 2)),
                Triple(Pair(1, 1), Direction.EAST, Pair(2, 1)),
                Triple(Pair(1, 1), Direction.SOUTH, Pair(1, 0)),
                Triple(Pair(1, 1), Direction.WEST, Pair(0, 1))
        )) {
            assertEquals(expected, pos + dir)
        }

    }
}
